# Generated by Django 5.1.6 on 2025-04-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
