# Generated by Django 5.1.6 on 2025-08-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0007_remove_product_created_at_remove_product_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('drink', 'Drink'), ('snack', 'Snack'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
