# Generated by Django 5.1.6 on 2025-08-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0008_product_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('sushi', 'Sushi'), ('salad', 'Salad'), ('drink', 'Drink'), ('desert', 'Desert')], default='other', max_length=20),
        ),
    ]
