# Generated by Django 5.2.4 on 2025-08-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0009_alter_product_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('pizza', 'Піца'), ('sushi', 'Суші'), ('salad', 'Салати'), ('drink', 'Напої'), ('desert', 'Десерти')], default='pizza', max_length=20),
        ),
    ]
