# Generated by Django 5.2.4 on 2025-08-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0010_alter_product_image_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('Піца', 'Піца'), ('Суші', 'Суші'), ('Салати', 'Салати'), ('Напої', 'Напої'), ('Десерти', 'Десерти')], default='pizza', max_length=20),
        ),
    ]
