# Generated by Django 5.2.4 on 2025-08-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0015_product_dislikes_product_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
    ]
