# Generated by Django 4.2.23 on 2025-08-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0017_customuser_bonus_points_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_bonus_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
