# Generated by Django 4.2.23 on 2025-08-10 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0018_cart_is_bonus_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_price', models.DecimalField(decimal_places=2, help_text='Ціна в бонусних балах', max_digits=8)),
                ('is_available', models.BooleanField(default=True, help_text='Доступний для бонусної покупки')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_info', to='Market.product')),
            ],
        ),
    ]
