# Generated by Django 4.2.23 on 2025-08-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0019_bonusproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusproduct',
            options={'verbose_name': 'Бонусний товар', 'verbose_name_plural': 'Бонусні товари'},
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_bonus_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
