# Generated by Django 4.2.23 on 2025-08-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0020_alter_bonusproduct_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_bonus_purchase',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='is_bonus_purchase',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='paid_with_bonus',
        ),
        migrations.DeleteModel(
            name='BonusProduct',
        ),
    ]
