# Generated by Django 4.2.23 on 2025-08-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0021_remove_cart_is_bonus_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bonus_points',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='bonus_points_earned',
        ),
    ]
